# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.access_grants.post import CreateGrantRaw
from vantage_python_sdk.paths.access_grants_access_grant_token.delete import DeleteRaw
from vantage_python_sdk.paths.access_grants_access_grant_token.get import GetSpecificGrantRaw
from vantage_python_sdk.paths.access_grants.get import ListAccessibleRaw
from vantage_python_sdk.paths.access_grants_access_grant_token.put import UpdateGrantTokenRaw


class AccessGrantsApiRaw(
    CreateGrantRaw,
    DeleteRaw,
    GetSpecificGrantRaw,
    ListAccessibleRaw,
    UpdateGrantTokenRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
