# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.business_metrics.post import CreateNewMetricRaw
from vantage_python_sdk.paths.business_metrics_business_metric_token.delete import DeleteExistingMetricRaw
from vantage_python_sdk.paths.business_metrics.get import GetAllMetricsRaw
from vantage_python_sdk.paths.business_metrics_business_metric_token.get import GetMetricByIdRaw
from vantage_python_sdk.paths.business_metrics_business_metric_token.put import UpdateExistingMetricRaw
from vantage_python_sdk.paths.business_metrics_business_metric_token_values_csv.put import UpdateValuesCsvRaw


class BusinessMetricsApiRaw(
    CreateNewMetricRaw,
    DeleteExistingMetricRaw,
    GetAllMetricsRaw,
    GetMetricByIdRaw,
    UpdateExistingMetricRaw,
    UpdateValuesCsvRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
