# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.dashboards.post import CreateDashboard
from vantage_python_sdk.paths.cost_reports.post import CreateReport
from vantage_python_sdk.paths.cost_reports_cost_report_token.delete import DeleteCostReport
from vantage_python_sdk.paths.dashboards_dashboard_token.delete import DeleteDashboard
from vantage_python_sdk.paths.dashboards.get import GetAll
from vantage_python_sdk.paths.cost_reports.get import GetAllCostReports
from vantage_python_sdk.paths.cost_reports_cost_report_token.get import GetCostReport
from vantage_python_sdk.paths.dashboards_dashboard_token.get import GetSpecificDashboard
from vantage_python_sdk.paths.costs.get import ListCostReport
from vantage_python_sdk.paths.dashboards_dashboard_token.put import UpdateDashboard
from vantage_python_sdk.paths.cost_reports_cost_report_token.put import UpdateReport
from vantage_python_sdk.apis.tags.costs_api_raw import CostsApiRaw


class CostsApi(
    CreateDashboard,
    CreateReport,
    DeleteCostReport,
    DeleteDashboard,
    GetAll,
    GetAllCostReports,
    GetCostReport,
    GetSpecificDashboard,
    ListCostReport,
    UpdateDashboard,
    UpdateReport,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CostsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CostsApiRaw(api_client)
