# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.dashboards.post import CreateDashboardRaw
from vantage_python_sdk.paths.dashboards_dashboard_token.delete import DeleteDashboardRaw
from vantage_python_sdk.paths.dashboards.get import GetAllRaw
from vantage_python_sdk.paths.dashboards_dashboard_token.get import GetSpecificDashboardRaw
from vantage_python_sdk.paths.dashboards_dashboard_token.put import UpdateDashboardRaw


class DashboardsApiRaw(
    CreateDashboardRaw,
    DeleteDashboardRaw,
    GetAllRaw,
    GetSpecificDashboardRaw,
    UpdateDashboardRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
