# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.dashboards.post import CreateDashboard
from vantage_python_sdk.paths.dashboards_dashboard_token.delete import DeleteDashboard
from vantage_python_sdk.paths.dashboards.get import GetAll
from vantage_python_sdk.paths.dashboards_dashboard_token.get import GetSpecificDashboard
from vantage_python_sdk.paths.dashboards_dashboard_token.put import UpdateDashboard
from vantage_python_sdk.apis.tags.dashboards_api_raw import DashboardsApiRaw


class DashboardsApi(
    CreateDashboard,
    DeleteDashboard,
    GetAll,
    GetSpecificDashboard,
    UpdateDashboard,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DashboardsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DashboardsApiRaw(api_client)
