# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.saved_filters.post import CreateSavedFilterForCostReports
from vantage_python_sdk.paths.saved_filters_saved_filter_token.delete import DeleteSavedFilter
from vantage_python_sdk.paths.saved_filters.get import GetCostReportFilters
from vantage_python_sdk.paths.saved_filters_saved_filter_token.get import GetSavedFilter
from vantage_python_sdk.paths.saved_filters_saved_filter_token.put import UpdateSavedFilterForCostReports
from vantage_python_sdk.apis.tags.filters_api_raw import FiltersApiRaw


class FiltersApi(
    CreateSavedFilterForCostReports,
    DeleteSavedFilter,
    GetCostReportFilters,
    GetSavedFilter,
    UpdateSavedFilterForCostReports,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FiltersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FiltersApiRaw(api_client)
