# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.saved_filters.post import CreateSavedFilterForCostReportsRaw
from vantage_python_sdk.paths.saved_filters_saved_filter_token.delete import DeleteSavedFilterRaw
from vantage_python_sdk.paths.saved_filters.get import GetCostReportFiltersRaw
from vantage_python_sdk.paths.saved_filters_saved_filter_token.get import GetSavedFilterRaw
from vantage_python_sdk.paths.saved_filters_saved_filter_token.put import UpdateSavedFilterForCostReportsRaw


class FiltersApiRaw(
    CreateSavedFilterForCostReportsRaw,
    DeleteSavedFilterRaw,
    GetCostReportFiltersRaw,
    GetSavedFilterRaw,
    UpdateSavedFilterForCostReportsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
