# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.folders.post import CreateFolderForCostReports
from vantage_python_sdk.paths.folders_folder_token.delete import DeleteFolderForCostReports
from vantage_python_sdk.paths.folders_folder_token.get import GetSpecificFolder
from vantage_python_sdk.paths.folders.get import ListCostReports
from vantage_python_sdk.paths.folders_folder_token.put import UpdateFolderForCostReports
from vantage_python_sdk.apis.tags.folders_api_raw import FoldersApiRaw


class FoldersApi(
    CreateFolderForCostReports,
    DeleteFolderForCostReports,
    GetSpecificFolder,
    ListCostReports,
    UpdateFolderForCostReports,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FoldersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FoldersApiRaw(api_client)
