# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.folders.post import CreateFolderForCostReportsRaw
from vantage_python_sdk.paths.folders_folder_token.delete import DeleteFolderForCostReportsRaw
from vantage_python_sdk.paths.folders_folder_token.get import GetSpecificFolderRaw
from vantage_python_sdk.paths.folders.get import ListCostReportsRaw
from vantage_python_sdk.paths.folders_folder_token.put import UpdateFolderForCostReportsRaw


class FoldersApiRaw(
    CreateFolderForCostReportsRaw,
    DeleteFolderForCostReportsRaw,
    GetSpecificFolderRaw,
    ListCostReportsRaw,
    UpdateFolderForCostReportsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
