# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.report_notifications.post import CreateReportNotificationRaw
from vantage_python_sdk.paths.report_notifications_report_notification_token.delete import DeleteReportNotificationRaw
from vantage_python_sdk.paths.report_notifications.get import GetAllReportNotificationsRaw
from vantage_python_sdk.paths.report_notifications_report_notification_token.get import GetReportNotificationRaw
from vantage_python_sdk.paths.report_notifications_report_notification_token.put import UpdateReportNotificationRaw


class NotificationsApiRaw(
    CreateReportNotificationRaw,
    DeleteReportNotificationRaw,
    GetAllReportNotificationsRaw,
    GetReportNotificationRaw,
    UpdateReportNotificationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
