# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.ping.get import HealthCheck
from vantage_python_sdk.apis.tags.ping_api_raw import PingApiRaw


class PingApi(
    HealthCheck,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PingApiRaw(api_client)
