# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.products_id.get import GetProduct
from vantage_python_sdk.paths.products_product_id_prices_id.get import GetProductPrice
from vantage_python_sdk.paths.products_product_id_prices.get import GetProductPrices
from vantage_python_sdk.paths.products.get import ListAvailableProducts
from vantage_python_sdk.apis.tags.prices_api_raw import PricesApiRaw


class PricesApi(
    GetProduct,
    GetProductPrice,
    GetProductPrices,
    ListAvailableProducts,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PricesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PricesApiRaw(api_client)
