# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.products_id.get import GetProductRaw
from vantage_python_sdk.paths.products_product_id_prices_id.get import GetProductPriceRaw
from vantage_python_sdk.paths.products_product_id_prices.get import GetProductPricesRaw
from vantage_python_sdk.paths.products.get import ListAvailableProductsRaw


class PricesApiRaw(
    GetProductRaw,
    GetProductPriceRaw,
    GetProductPricesRaw,
    ListAvailableProductsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
