# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.segments.post import CreateSegmentRaw
from vantage_python_sdk.paths.segments_segment_token.get import GetSegmentByIdRaw
from vantage_python_sdk.paths.segments.get import ListRaw
from vantage_python_sdk.paths.segments_segment_token.delete import RemoveSegmentRaw
from vantage_python_sdk.paths.segments_segment_token.put import UpdateSegmentByIdRaw


class SegmentsApiRaw(
    CreateSegmentRaw,
    GetSegmentByIdRaw,
    ListRaw,
    RemoveSegmentRaw,
    UpdateSegmentByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
