# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.teams.post import CreateNewTeam
from vantage_python_sdk.paths.teams_team_token.get import GetSpecificTeam
from vantage_python_sdk.paths.teams.get import ListAccessible
from vantage_python_sdk.paths.teams_team_token.delete import RemoveTeam
from vantage_python_sdk.paths.teams_team_token.put import UpdateTeam
from vantage_python_sdk.apis.tags.teams_api_raw import TeamsApiRaw


class TeamsApi(
    CreateNewTeam,
    GetSpecificTeam,
    ListAccessible,
    RemoveTeam,
    UpdateTeam,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TeamsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TeamsApiRaw(api_client)
