# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.teams.post import CreateNewTeamRaw
from vantage_python_sdk.paths.teams_team_token.get import GetSpecificTeamRaw
from vantage_python_sdk.paths.teams.get import ListAccessibleRaw
from vantage_python_sdk.paths.teams_team_token.delete import RemoveTeamRaw
from vantage_python_sdk.paths.teams_team_token.put import UpdateTeamRaw


class TeamsApiRaw(
    CreateNewTeamRaw,
    GetSpecificTeamRaw,
    ListAccessibleRaw,
    RemoveTeamRaw,
    UpdateTeamRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
