# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.users_user_token.get import GetSpecificUser
from vantage_python_sdk.paths.users.get import ListAccessible
from vantage_python_sdk.apis.tags.users_api_raw import UsersApiRaw


class UsersApi(
    GetSpecificUser,
    ListAccessible,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UsersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UsersApiRaw(api_client)
