# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.users_user_token.get import GetSpecificUserRaw
from vantage_python_sdk.paths.users.get import ListAccessibleRaw


class UsersApiRaw(
    GetSpecificUserRaw,
    ListAccessibleRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
