# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.workspaces_workspace_token.get import GetSpecificWorkspaceRaw
from vantage_python_sdk.paths.workspaces.get import ListAccessibleRaw


class WorkspacesApiRaw(
    GetSpecificWorkspaceRaw,
    ListAccessibleRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
