# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from vantage_python_sdk.paths.workspaces_workspace_token.get import GetSpecificWorkspace
from vantage_python_sdk.paths.workspaces.get import ListAccessible
from vantage_python_sdk.apis.tags.workspaces_api_raw import WorkspacesApiRaw


class WorkspacesApi(
    GetSpecificWorkspace,
    ListAccessible,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WorkspacesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WorkspacesApiRaw(api_client)
