# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vantage_python_sdk import schemas  # noqa: F401


class BusinessMetrics(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    BusinessMetrics model
    """


    class MetaOapg:
        
        class properties:
            
            
            class business_metrics(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['BusinessMetric']:
                        return BusinessMetric
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['BusinessMetric'], typing.List['BusinessMetric']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'business_metrics':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'BusinessMetric':
                    return super().__getitem__(i)
            __annotations__ = {
                "business_metrics": business_metrics,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["business_metrics"]) -> MetaOapg.properties.business_metrics: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["business_metrics", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["business_metrics"]) -> typing.Union[MetaOapg.properties.business_metrics, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["business_metrics", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        business_metrics: typing.Union[MetaOapg.properties.business_metrics, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BusinessMetrics':
        return super().__new__(
            cls,
            *args,
            business_metrics=business_metrics,
            _configuration=_configuration,
            **kwargs,
        )

from vantage_python_sdk.model.business_metric import BusinessMetric
