# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vantage_python_sdk import schemas  # noqa: F401


class PutBusinessMetricsValues(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    The dates and amounts for the BusinessMetric.
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['PutBusinessMetricsValuesItem']:
            return PutBusinessMetricsValuesItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['PutBusinessMetricsValuesItem'], typing.List['PutBusinessMetricsValuesItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'PutBusinessMetricsValues':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'PutBusinessMetricsValuesItem':
        return super().__getitem__(i)

from vantage_python_sdk.model.put_business_metrics_values_item import PutBusinessMetricsValuesItem
