# coding: utf-8

"""
    Vantage

    Vantage API

    The version of the OpenAPI document: 2.0.0
    Contact: support@vantage.sh
    Created by: https://www.vantage.sh
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vantage_python_sdk import schemas  # noqa: F401


class Team(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Team model
    """


    class MetaOapg:
        
        class properties:
            description = schemas.StrSchema
            token = schemas.StrSchema
            name = schemas.StrSchema
        
            @staticmethod
            def workspace_tokens() -> typing.Type['TeamWorkspaceTokens']:
                return TeamWorkspaceTokens
        
            @staticmethod
            def user_emails() -> typing.Type['TeamUserEmails']:
                return TeamUserEmails
        
            @staticmethod
            def user_tokens() -> typing.Type['TeamUserTokens']:
                return TeamUserTokens
            __annotations__ = {
                "description": description,
                "token": token,
                "name": name,
                "workspace_tokens": workspace_tokens,
                "user_emails": user_emails,
                "user_tokens": user_tokens,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["token"]) -> MetaOapg.properties.token: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["workspace_tokens"]) -> 'TeamWorkspaceTokens': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user_emails"]) -> 'TeamUserEmails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user_tokens"]) -> 'TeamUserTokens': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["description", "token", "name", "workspace_tokens", "user_emails", "user_tokens", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["token"]) -> typing.Union[MetaOapg.properties.token, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["workspace_tokens"]) -> typing.Union['TeamWorkspaceTokens', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user_emails"]) -> typing.Union['TeamUserEmails', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user_tokens"]) -> typing.Union['TeamUserTokens', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["description", "token", "name", "workspace_tokens", "user_emails", "user_tokens", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        token: typing.Union[MetaOapg.properties.token, str, schemas.Unset] = schemas.unset,
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        workspace_tokens: typing.Union['TeamWorkspaceTokens', schemas.Unset] = schemas.unset,
        user_emails: typing.Union['TeamUserEmails', schemas.Unset] = schemas.unset,
        user_tokens: typing.Union['TeamUserTokens', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Team':
        return super().__new__(
            cls,
            *args,
            description=description,
            token=token,
            name=name,
            workspace_tokens=workspace_tokens,
            user_emails=user_emails,
            user_tokens=user_tokens,
            _configuration=_configuration,
            **kwargs,
        )

from vantage_python_sdk.model.team_user_emails import TeamUserEmails
from vantage_python_sdk.model.team_user_tokens import TeamUserTokens
from vantage_python_sdk.model.team_workspace_tokens import TeamWorkspaceTokens
